### PR TITLE
3D Printing Catchup

### PR DESCRIPTION
**Pull request by rbsecor**
Update of 3D printing thermal expansion mods including ORIENTATION vectors in post-processing, hard-coded for now.  I'll have to make that input file connected soon.  Thermal expansion model updates for NONLINEAR and KELVIN-VOIGT models.  Removal of some old, deprecated "SECOR_HEAT_FLUX" defines.  That capability is now included in the lubrication shell capability.  Also, first check-in of a lubrication wall drag bc -- not tested yet.

### CODE REVIEW

**Comment by wortiz** [comment]
I can run clang-format if need be that seems to be the only checks failing. After I look at the rest of the code.

If you have clang format 15 or later it seems like they changed some stuff that makes it incompatible.

**Review by wortiz — APPROVED** [review]

**Comment by rbsecor** [comment]
I have some things I forgot to update, i.e. removing hard-coded parameters.  I'll check the clang-format version, etc.

**Comment by rbsecor** [comment]
It looks like I'm running clang-format v14, so it should be OK

**Comment by rbsecor** [comment]
FYI, added bugfix for User-Defined Post Processing.

**Comment by wortiz** [comment]
Is this ready to be merged?

**Comment by rbsecor** [comment]
Yes, I'm done for now. RobertOn Jan 20, 2023 12:06 PM, Weston Ortiz ***@***.***> wrote:
Is this ready to be merged?

**Pull request merged**
