### PR TITLE
Goma7

### PR DESCRIPTION
**Pull request by rbsecor**
Various updates around the time of Goma7 release:
1.  Revamping of hunting to accommodate negative parameters, etc.
2.  First phase of shear-thinning lubrication for fixed walls
3.  Orthotropic thermal expansion model
4. Various bugfixes and compiler warning fixes
5. User initialization via blocks

### CODE REVIEW

**Comment by wortiz** [comment]
I'm thinking most of the failures are from calculate_lub_q_v

The two psat failures psat_rdl and psat_ant I'm unsure of maybe the initialize change?

I'll try to look at it in more detail tomorrow.

**Comment by rbsecor** [comment]
Oh, I see.  I need to replicate lub changes to the film and other models since I changes assemble_lubrication...

**Comment by rbsecor** [comment]
OK, I'll look over the lub_shell problem...

**Comment by rbsecor** [comment]
p.s. And I need to make the user material initialization more general.

**Pull request merged**
